name: 'release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd' # v5.0.1
        with:
          fetch-depth: 0

      - uses: 'actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5' # v6.2.0
        with:
          go-version: 'stable'

      - id: 'import_gpg'
        uses: 'crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec' # v6.3.0
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          passphrase: '${{ secrets.PASSPHRASE }}'

      - uses: 'goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a' # v6.4.0
        with:
          version: 'v1.14.1'
          args: 'release --rm-dist'
        env:
          GPG_FINGERPRINT: '${{ steps.import_gpg.outputs.fingerprint }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
